version: "3.8"
services:
  # app
  app:
    build: ./infrastructure/app
    volumes:
      - ./backend:/work
  # web
  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infrastructure/web/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  # db
  db:
    build: ./infrastructure/db
    volumes:
      - db-store:/var/lib/mysql
volumes:
  db-store: